### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by llantones** [axel-angel/whatsapp-email-bridge#26]
Hello:
Still work this program?
If yes, where copy the file:
"cp config.yaml.example config.yaml"
and how to use it? How send a message and how receive a message?
Thanks

**Comment by axel-angel** [comment]
Hi, this is an old program and isn't maintained anymore. Feel free to try and report if it's still work for you.

**Comment by PikachuEXE** [comment]
@axel-angel Maybe add a line in README to state that this project is not maintained?
