### ISSUE TITLE
Add support for IMAP forwarding (eg: for Gmail)

### ISSUE THREAD

**Issue by ghost** [axel-angel/whatsapp-email-bridge#3]
Original title: Email port number not included

**Comment by axel-angel** [comment]
The way the actual program works is by creating a unix domain socket (a file) that listen for emails, it uses the standard LMTP protocol. Fortunately it's easy to switch to real socket (with port). I can make an option for this, is that what you are asking for?

As a side note, if you are using gmail (which seems to be), even after you have this port opened, gmail will probably not be able to reach it to send your email. What you probably want is a different method to "listen" to incoming emails (to forward them on WhatsApp) directly integrated with gmail, for example using IMAP (with IDLE), that's a bit of work. If you are interested, just create an issue for this and I will try to make this happens.

**Comment by axel-angel** [comment]
@ghost Hello, IMAP is now supported protocol! Feel free to test it.
