### ISSUE TITLE
about setting up the script

### ISSUE THREAD

**Issue by jansoncws** [axel-angel/whatsapp-email-bridge#7]
Hi,

I know nothing about the script, can i know how could i set it up? or any freelancer can help?

thank you

**Comment by axel-angel** [comment]
Hello,

Have you tried to read and follow the steps in the README: https://github.com/axel-angel/whatsapp-email-bridge/blob/master/README

This project is only at its early stages, feel free to contribute to the instructions if they aren't clear enough.

**Comment by axel-angel** [comment]
More than 3 weeks passed with no reply, I'm closing for now. Feel free to reopen.
